### ISSUE TITLE
Funcion toast en ultima versión javascript.js rompe la funcion toast de APP7

### ISSUE THREAD

**Issue by mlaborde** [CloudyVisionArg/cdn#1]
**Detalle:**
La función "toast" agregada en javascript.js rompe la función toast en la APP7, mostrando error de que se requiere Bootstrap 5 o superior

**Pasos para reproducir:**
1 - Incluir javascript.js en generic/codelib de la APP7
2 - Guardar documento
Esta acción no muestra el mensaje de Cambios guardados OK/Errores de guardado

**Workaround:**
Incluir versión 66 de javascript.js, en donde no se encuentra la función toast nueva

**Nota:**
Probado en APP Grupo Edisur -> Oportunidades

**Comment by pagano** [comment]
La biblioteca javascript es para la web, no para el APP, ya que trabaja con Bootstrap. Si es necesario alguna funcion de la misma incluirla en el global custom y solicitar el alta en global.js

**Comment by pagano** [comment]
Voy a pasar

**Comment by pagano** [comment]
Corregido, la nueva biblioteca se llama jslib
