### ISSUE TITLE
DTPicker - Cambio de fecha para horas después de las 21

### ISSUE THREAD

**Issue by mlaborde** [CloudyVisionArg/cdn#10]
Los DTPicker (fecha y hora) están cambiando la fecha a un día posterior cuando la hora es mayor a las 21hs

Al parecer esto está relacionado con la nueva doorsapi y los valores de los fields
Al parecer esta funcion está preparada para recibir un texto y está recibiendo un objeto
https://github.com/CloudyVisionArg/cdn/blob/b36ca411575de2c0e49e4ef55d51fea0cc069fe6/app7/controls.js#L700

**Como reproducir**
Abrir App free, abrir oportunidad y poner fecha prox acción a las 21:30 por ejemplo y guardar.
Al abrir de nuevo esa oportunidad la fecha va a tener un día más.

**Comment by pagano** [comment]
Bug jslib.ISODate
