### ISSUE TITLE
APP - ValueChanged en campos vacíos

### ISSUE THREAD

**Issue by mlaborde** [CloudyVisionArg/cdn#16]
Al guardar un documento desde el generic de la APP, un campo (con control de texto) que tenía null, se está cambiando a "" (string vacío) por lo que se reporta ValueChanged el field
Debería quedar con null
Se puede probar en Cabrera al querer bloquear un producto con el Test User, donde solo se puede cambiar el estado y el cliente

**Comment by mlaborde** [comment]
Como workaround en el código le agregué
```
If field.Value & "" <> field.ValueOld & "" Then
End If
```

**Comment by pagano** [comment]
doorsapi2 v285
Cdo se asigna un '' a un campo de texto el valor se pasa a null
