### ISSUE TITLE
Soporte para input type='email'

### ISSUE THREAD

**Issue by SantiagoPagnone** [CloudyVisionArg/cdn#17]
En las apps cambiamos el type de los controles textbox a email para que se validen los formatos de email valido
Cuando se modifica el type del textbox no se bindea al campo cuando se guarda.

Creo que deberia haber un or que contemple type == 'email'

https://github.com/CloudyVisionArg/cdn/blob/57c45908a91d3d54a244bf530b47363b9c8912cc/app7/generic.js#L1590

**Comment by pagano** [comment]
Listo. Tag 290. Le agregue email y password
