### ISSUE TITLE
Obtener DocLog solo si hay controles documentLog?

### ISSUE THREAD

**Issue by mlaborde** [CloudyVisionArg/cdn#3]
Viendo en el código, se obtiene siempre el documentLog y en algunos documentos es bastante pesado
Quizás estaría bueno que no se obtenga siempre, sino solo si hay algún control docLog

**Comment by pagano** [comment]
En el generic del app?

**Comment by mlaborde** [comment]
Exacto! Sería en la funcion fillControls()

**Comment by pagano** [comment]
Resuelto tag 113
